
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Mon Feb 01 15:16:38 CET 2016
//----------------------------------------------------

package petter.simplec;

/** CUP generated interface containing symbol constants. */
public interface sym {
  /* terminals */
  public static final int DIVEQ = 36;
  public static final int COMMENT = 47;
  public static final int QUESTIONMARK = 24;
  public static final int CASE = 13;
  public static final int SEMI = 45;
  public static final int HASH = 8;
  public static final int CONTINUE = 10;
  public static final int INT = 2;
  public static final int FOR = 6;
  public static final int AND = 38;
  public static final int NOT = 31;
  public static final int LT = 42;
  public static final int RPAR = 23;
  public static final int DECOP = 26;
  public static final int INTCONST = 48;
  public static final int OR = 37;
  public static final int COMMA = 18;
  public static final int BEGIN = 20;
  public static final int MULOP = 29;
  public static final int GEQ = 39;
  public static final int PLUSEQ = 33;
  public static final int MINUSEQ = 34;
  public static final int ASSIGN = 44;
  public static final int IF = 16;
  public static final int EOF = 0;
  public static final int RETURN = 4;
  public static final int PRAGMA = 7;
  public static final int error = 1;
  public static final int NEQ = 41;
  public static final int IDENT = 49;
  public static final int BREAK = 9;
  public static final int VOID = 3;
  public static final int EQ = 32;
  public static final int ADDOP = 27;
  public static final int MULEQ = 35;
  public static final int SWITCH = 14;
  public static final int INCOP = 25;
  public static final int COLON = 19;
  public static final int ILLEGAL = 46;
  public static final int ELSE = 17;
  public static final int GOTO = 11;
  public static final int WHILE = 15;
  public static final int DIVOP = 30;
  public static final int DEFAULT = 12;
  public static final int LEQ = 40;
  public static final int END = 21;
  public static final int LPAR = 22;
  public static final int SUBOP = 28;
  public static final int GT = 43;
  public static final int DO = 5;
}

