
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20150930 (SVN rev 66)
//----------------------------------------------------

package petter.simplec;

/** CUP generated interface containing symbol constants. */
public interface sym {
  /* terminals */
  public static final int DIVEQ = 46;
  public static final int SHORT = 8;
  public static final int CHAR = 4;
  public static final int COMMENT = 57;
  public static final int QUESTIONMARK = 34;
  public static final int CASE = 20;
  public static final int DOUBLE = 5;
  public static final int SEMI = 55;
  public static final int HASH = 15;
  public static final int CONTINUE = 17;
  public static final int TYPE_NAME = 9;
  public static final int INT = 2;
  public static final int FOR = 13;
  public static final int LSQ = 31;
  public static final int AND = 48;
  public static final int NOT = 41;
  public static final int LT = 52;
  public static final int RPAR = 30;
  public static final int DECOP = 36;
  public static final int ADDOFOP = 33;
  public static final int INTCONST = 58;
  public static final int OR = 47;
  public static final int COMMA = 25;
  public static final int MULOP = 39;
  public static final int BEGIN = 27;
  public static final int GEQ = 49;
  public static final int PLUSEQ = 43;
  public static final int MINUSEQ = 44;
  public static final int TYPEDEF = 10;
  public static final int ASSIGN = 54;
  public static final int IF = 23;
  public static final int EOF = 0;
  public static final int RETURN = 11;
  public static final int PRAGMA = 14;
  public static final int error = 1;
  public static final int RSQ = 32;
  public static final int NEQ = 51;
  public static final int IDENT = 59;
  public static final int BREAK = 16;
  public static final int VOID = 3;
  public static final int EQ = 42;
  public static final int ADDOP = 37;
  public static final int MULEQ = 45;
  public static final int SWITCH = 21;
  public static final int INCOP = 35;
  public static final int COLON = 26;
  public static final int ILLEGAL = 56;
  public static final int ELSE = 24;
  public static final int GOTO = 18;
  public static final int WHILE = 22;
  public static final int DIVOP = 40;
  public static final int DEFAULT = 19;
  public static final int FLOAT = 6;
  public static final int LEQ = 50;
  public static final int END = 28;
  public static final int LONG = 7;
  public static final int LPAR = 29;
  public static final int SUBOP = 38;
  public static final int GT = 53;
  public static final int DO = 12;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "INT",
  "VOID",
  "CHAR",
  "DOUBLE",
  "FLOAT",
  "LONG",
  "SHORT",
  "TYPE_NAME",
  "TYPEDEF",
  "RETURN",
  "DO",
  "FOR",
  "PRAGMA",
  "HASH",
  "BREAK",
  "CONTINUE",
  "GOTO",
  "DEFAULT",
  "CASE",
  "SWITCH",
  "WHILE",
  "IF",
  "ELSE",
  "COMMA",
  "COLON",
  "BEGIN",
  "END",
  "LPAR",
  "RPAR",
  "LSQ",
  "RSQ",
  "ADDOFOP",
  "QUESTIONMARK",
  "INCOP",
  "DECOP",
  "ADDOP",
  "SUBOP",
  "MULOP",
  "DIVOP",
  "NOT",
  "EQ",
  "PLUSEQ",
  "MINUSEQ",
  "MULEQ",
  "DIVEQ",
  "OR",
  "AND",
  "GEQ",
  "LEQ",
  "NEQ",
  "LT",
  "GT",
  "ASSIGN",
  "SEMI",
  "ILLEGAL",
  "COMMENT",
  "INTCONST",
  "IDENT"
  };
}

